-- Notas adicionales:
-- 1. El tipo de dato SERIAL crea una secuencia que se incrementa automáticamente con cada inserción.
-- 2. Es posible insertar manualmente valores en "user_id" siempre y cuando no se repitan.
-- 3. Si se insertan valores manuales que saltan la secuencia, PostgreSQL intentará continuar desde el último valor de la secuencia.
-- 4. Si la secuencia alcanza un valor ya existente, se producirá un error.

CREATE TABLE "users" (
    "user_id" SERIAL PRIMARY KEY, -- ID autoincrementable que se incrementa automáticamente
    "username" VARCHAR( 100 )       -- Nombre de usuario con un máximo de 100 caracteres
);

-- Permite colocar distintos tipos de datos como ID
CREATE TABLE "users2" (
	"user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"username" VARCHAR( 100 )
);

-- De esta manera hacemos que no se puedan colocar IDs manualmente
CREATE TABLE "users3" (
	"user_id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"username" VARCHAR( 100 )
);

-- Indicar desde donde iniciara a contar el id y de cuanto en cuanto
CREATE TABLE "users4" (
	"user_id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 2 ) PRIMARY KEY,
	"username" VARCHAR( 100 )
);

CREATE TABLE "users5" (
	"user_id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 2 ) PRIMARY KEY,
	"username" VARCHAR( 100 )
);